version: '3'
services:
  postgres:
    image: postgres:13.1-alpine
    expose:
      - '5432'
    volumes:
      - type: volume
        source: pg-db-data
        target: /data/db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
  redis:
    image: 'redis:6.0.9'
  api:
    expose:
      - '3030'
    build:
      dockerfile: Dockerfile
      context: ./server
      target: debug
    depends_on:
      - postgres
      - redis
    volumes:
      - /app/node_modules
      - ./server/src:/app
    environment:
      - PORT=3030
      - DB_TYPE=pg
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_PASSWORD=
      - REDIS_FAMILY=4
      - SHOW_ERRORS=false
      - APP_URI=http://localhost:3030
      - UPLOADS_PUBLIC_URL=http://localhost:3030
    ports:
      - '3030:3030'
      - '9229:9229'
  dashboard:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./dashboard
      args:
        - REACT_APP_BASE_URL=http://localhost:3030/
    depends_on:
      - api
    volumes:
      - ./dashboard/src:/node/app
      - /node/app/node_modules
    expose:
      - '3333'
    ports:
      - '3333:3333'

volumes:
  pg-db-data:
